# Generated by Django 3.2.5 on 2021-08-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivingScience',
            fields=[
                ('apartment_nr', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmation', models.BooleanField(default=False)),
                ('rentmin', models.PositiveIntegerField(default=300)),
                ('rentmax', models.PositiveIntegerField(default=1000)),
                ('earlieststartdate', models.DateField(default=django.utils.timezone.now)),
                ('woko', models.BooleanField(default=False)),
                ('ls', models.BooleanField(default=False)),
                ('wohnen', models.BooleanField(default=False)),
                ('wg', models.BooleanField(default=False)),
                ('studio', models.BooleanField(default=False)),
                ('flat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WohnenUZHETHZ',
            fields=[
                ('apartment_nr', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WOKO',
            fields=[
                ('link_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
